"use client";

import React from 'react';
import Layout from '@/components/Layout';
import DashboardCard from '@/components/DashboardCard';
import { motion } from 'framer-motion';
import { cn } from "@/lib/utils";
import { 
  Lightbulb, 
  CheckCircle2, 
  ArrowRight, 
  Zap, 
  Target, 
  Users,
  MapPin,
  Clock
} from 'lucide-react';

const recommendations = [
  {
    title: "Optimize Bin Placement",
    description: "AI analysis shows high footfall in Sector 12 Park. Adding 3 smart bins here will reduce littering by 40%.",
    impact: "High Impact",
    category: "Infrastructure",
    icon: MapPin,
    color: "text-emerald-500",
    bg: "bg-emerald-500/10"
  },
  {
    title: "Adjust Collection Timing",
    description: "Shift collection in Ward 4 to 6:00 AM to avoid traffic congestion and improve fuel efficiency.",
    impact: "Medium Impact",
    category: "Logistics",
    icon: Clock,
    color: "text-blue-500",
    bg: "bg-blue-500/10"
  },
  {
    title: "Community Engagement",
    description: "Launch a composting workshop in Skyline Apartments. Predicted 2-ton reduction in wet waste monthly.",
    impact: "High Impact",
    category: "Social",
    icon: Users,
    color: "text-purple-500",
    bg: "bg-purple-500/10"
  },
  {
    title: "E-Waste Drive",
    description: "Schedule a specialized e-waste collection drive next Saturday. High accumulation detected in Sector 10.",
    impact: "Medium Impact",
    category: "Specialized",
    icon: Zap,
    color: "text-amber-500",
    bg: "bg-amber-500/10"
  }
];

const Recommendations = () => {
  return (
    <Layout>
      <div className="space-y-8">
        <div className="max-w-3xl">
          <h1 className="text-4xl font-bold mb-2">AI Recommendations</h1>
          <p className="text-gray-400">Actionable strategies generated by our neural engine to optimize waste management and community impact.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {recommendations.map((rec, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1 }}
            >
              <DashboardCard className="h-full flex flex-col">
                <div className="flex justify-between items-start mb-6">
                  <div className={cn("p-3 rounded-2xl", rec.bg)}>
                    <rec.icon className={rec.color} size={24} />
                  </div>
                  <span className={cn(
                    "text-[10px] font-black px-2 py-1 rounded-lg bg-white/5",
                    rec.impact === 'High Impact' ? "text-emerald-500" : "text-blue-500"
                  )}>
                    {rec.impact.toUpperCase()}
                  </span>
                </div>
                
                <h3 className="text-xl font-bold mb-2">{rec.title}</h3>
                <p className="text-sm text-gray-400 mb-6 flex-grow">{rec.description}</p>
                
                <div className="flex items-center justify-between mt-auto pt-6 border-t border-white/5">
                  <span className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">{rec.category}</span>
                  <button className="text-emerald-500 font-bold text-sm flex items-center gap-2 hover:translate-x-1 transition-transform">
                    Implement Plan <ArrowRight size={16} />
                  </button>
                </div>
              </DashboardCard>
            </motion.div>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <DashboardCard className="lg:col-span-2" title="Optimization Roadmap" subtitle="Next 30 days strategy">
            <div className="relative py-10">
              <div className="absolute top-1/2 left-0 w-full h-0.5 bg-emerald-500/10 -translate-y-1/2" />
              <div className="flex justify-between relative z-10">
                {['Analyze', 'Propose', 'Execute', 'Review'].map((step, i) => (
                  <div key={i} className="flex flex-col items-center gap-4">
                    <div className={cn(
                      "w-12 h-12 rounded-full flex items-center justify-center font-bold border-2",
                      i === 0 ? "bg-emerald-500 border-emerald-500 text-black" : "bg-black border-white/10 text-gray-500"
                    )}>
                      {i + 1}
                    </div>
                    <span className="text-xs font-bold">{step}</span>
                  </div>
                ))}
              </div>
            </div>
            <div className="mt-6 p-6 rounded-2xl bg-emerald-500/5 border border-emerald-500/20 flex gap-4">
              <Lightbulb className="text-emerald-500 shrink-0" size={24} />
              <p className="text-sm text-gray-300 leading-relaxed">
                Our AI suggests that focusing on <span className="text-emerald-500 font-bold">Wet Waste Segregation</span> in the next 14 days will yield the highest ROI for the city's Green Credit score.
              </p>
            </div>
          </DashboardCard>

          <DashboardCard title="Efficiency Score" subtitle="Current vs Potential">
            <div className="flex flex-col items-center py-6">
              <div className="relative w-40 h-40">
                <svg className="w-full h-full" viewBox="0 0 100 100">
                  <circle cx="50" cy="50" r="45" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="10" />
                  <circle cx="50" cy="50" r="45" fill="none" stroke="#10b981" strokeWidth="10" strokeDasharray="283" strokeDashoffset="85" strokeLinecap="round" />
                  <circle cx="50" cy="50" r="35" fill="none" stroke="rgba(59,130,246,0.2)" strokeWidth="10" strokeDasharray="220" strokeDashoffset="44" strokeLinecap="round" />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <span className="text-3xl font-black">70%</span>
                  <span className="text-[10px] font-bold text-gray-500">CURRENT</span>
                </div>
              </div>
              <div className="mt-8 space-y-3 w-full">
                <div className="flex justify-between text-xs">
                  <span className="text-gray-400">Potential with AI</span>
                  <span className="text-emerald-500 font-bold">94%</span>
                </div>
                <div className="w-full bg-white/5 h-2 rounded-full overflow-hidden">
                  <div className="bg-emerald-500 h-full w-[70%]" />
                </div>
              </div>
            </div>
          </DashboardCard>
        </div>
      </div>
    </Layout>
  );
};

export default Recommendations;